version: '3'

services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./mongodb-data:/data/db
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front:/app
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    volumes:
      - ./back:/app
